### ISSUE TITLE
No caching.

### ISSUE THREAD

**Issue by StephenLynx** [fatchan/jschan#10]
Board pages and thread pages always return a HTTP code 200. I was going to originally report that multiple pages would be served from the same URI (domain/b and domain/b/) and that duplicates cache, but I noticed there is no cache at all.

**Comment by fatchan** [comment]
1. Yes, I am aware. All the pages are generated on demand.
2. View caching is disabled so that also contributes significantly to the site feeling slower since every request reads the template files from disk again. (this is so i can edit templates without server restart while developing)

As for caching solution, Pug (formerly jade) template engine has `renderFile` method that outputs the raw html. I could save that to database or file to serve instead on subsequent requests. then invalidate those when a new post is made in that thread/board. Does this seem reasonable?

Just because it doesnt do any caching yet doesn't mean im forgetting :wink: dont take the performance of the site too seriously in its current state.

**Comment by StephenLynx** [comment]
I used to store cache on mongo and it isn't a great idea because gridfs doesn't handle concurrency too well. Besides, it impacts performance. Caching on access and invalidating on change is a better solution than invalidating and caching on change, in my experience because I've been there and done that. And you forgot to address the same page being served on multiple URIs.

Now, where to store the cahe? I don't have a solid answer for that. Even my current solution have it's drawbacks and gave up performance when it came to high concurrency scenarios, despite performance gains on low concurrency scenarios.

As for CSRF, I don't like using tokens for that, SPECIALLY for pages that are cached. Vichan does something similar to fight spam and it ends up with a bunch of false positives. I don't think it's much of an issue for someone to fall for a CSRF that results in making a simple post. The user will realize and delete the post.

**Comment by fatchan** [comment]
OK. I appreciate input on caching options.

As for duplicate url, I could use nginx to rewrite and strip trailing slash if necessary. I wouldnt cache same page twice anyway since express handles url with trailing slash by same route.

**Comment by StephenLynx** [comment]
Yeah, a simple 302 redirect (never use 301) should suffice. For one, I redirect uris without slash to the slashed one, to keep consistency with the other pages. If you redirect to non-slash, it will live in the root directory, making relative uris invalid between the other pages that live in the board directory.
For example:

domain/b/2.html with the relative uri catalog.html will take you to domain/b/catalog.html
domain/b with the same relative uri will try to take you to domain/catalog.html. 

This is why other engines do the same and redirect to the slashed one.

As for CSRF, I just check for the referrer if the action should be authenticated and fail user authentication if referrer doesn't match.

**Comment by fatchan** [comment]
Good point on trailing slashes for relative URLs. Never thought about that. I guess i was too eager for the clean url without slash :sweat_smile: 

Im still reluctant to remove csurf module, but for cached pages it will _probably_ cause issues. Making a middleware to check the referrer is super simple in express. Ill do a little more research and see how reliable that is.

Gonna close this now. I think that covers everything. Feel free to re-open or make other issue for any problems.
