### ISSUE TITLE
Impossible to refresh captcha with JS disabled on Pale Moon

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#155]
When using Pale Moon and having JavaScript disabled, it is impossible to request a new captcha on the Block bypass page. Both using the F5 method and clicking the little refresh arrow in the corner of the captcha.
The browser console has this to say (not sure if it's relevant): `The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  captcha.html`

**Comment by fatchan** [comment]
With JS disabled, what happens inside the frame is:
1. Refresh button submits to /newcaptcha
2. Response from /newcaptcha clears `captchaid` cookie and redirects to /captcha.html
3. captcha.html contains an `<img src="/captcha"`, which serves a new captcha because you no longer have a `captchaid` cookie.

Palemoon breaks on 3 because it never reloads the image after the page refreshes. I'll fix it when somebody gives the actual reason palemoon (or any browser) acts this way, otherwise I consider it a browser issue.

The missing character encoding is unrelated

**Comment by hawkoon** [comment]
What's weird is that when you manually right-click the captcha image and then click View image, it shows you the new captcha (so different from the one that is currently displaying on the page). And when you THEN, after having done that, click the little refresh arrow after you have retrieved the .jpg file it **does** refresh. Very strange.

Also again not sure if related but console says:
Content Security Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSU... (“img-src https://site.name blob:”).  
(unknown)

**Comment by fatchan** [comment]
That CSP violation would cause issues, but jschan doesn't use a data:image uri anywhere. That's probably from the the "view image" page. 
But why the image only refreshes after doing that is indeed very strange.

Sounds like a different caching behaviour or bug in palemoon? But weirdly the network tab doesnt even show a "cached" request for the image (like it DOES for the css file) on captcha.html. In fact, it doesn't make a request at all. ¯\_ (ツ) _/¯

**Comment by hawkoon** [comment]
Hm. Maybe I'll contact the Pale Moon folks to see if they can assist.

**Comment by fatchan** [comment]
Just checked and the issue is also present in [Basilisk](https://basilisk-browser.org/), another browser made by same dev team as palemoon.

**Comment by hawkoon** [comment]
The lead Pale Moon developer replied:

> Analysis in no-javascript mode:
> 
>     1. /newcaptcha 302-redirects to /captcha.html and sets the following cookie:
>     captchaid=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
>     This effectively removes the cookie.
>     2. /captcha.html 200-OK
>     3. /captcha (img-src in captcha.html) is unknown and requested: 302-redirects to a specific image and sets a captchaID cookie
>     the ID is equal to the file name requested in the 302 minus .jpg
>     4. The image served has a long-duration cache directive and is stored in the browser's cache as a result.
>     5. Clicking the refresh sends a new cookie-clear
>     6. /captcha.html 200-OK
>     7. /captcha (img-src in captcha.html) is known as a cached image -> the cached image will be served
> 
> The cookie is effectively not used and is irrelevant to this sequence.
> 
> This is a server-side issue that can be solved several ways:
> 
>    -no-store solution: If the captcha image is not supposed to be stored in cache, then the web server should send a cache directive accordingly (and not a long-duration image cache directive)
>     -captcha.html could be dynamic (directly linking to the target image) and not use a 302 redirect to a fixed name /captcha.

**Comment by fatchan** [comment]
Hey, 

/captcha being "known as a cached image" just because it recirects to a location with long cache directive seems weird. I checked the [RFC](https://www.rfc-editor.org/rfc/rfc7231.txt) (section 6.4.3 I think is the relevant part)
>  The 302 (Found) status code indicates that the target resource
>    resides temporarily under a different URI.  Since the redirection
>    might be altered on occasion, the client ought to continue to use the
>    effective request URI for future requests.
>
>  The server SHOULD generate a Location header field in the response
>    containing a URI reference for the different URI.  The user agent MAY
>    use the Location field value for automatic redirection.  The server's
>    response payload usually contains a short hypertext note with a
>    hyperlink to the different URI(s).

but I'm still not sure. Other browsers behave how I would expect, but who am I to dictate what is correct or suggest that they should have the same behaviour? 

Anyway, the easiest thing to do is not cache captcha images.I'm no longer updating this repo and will most likely archive it. Adding this to your nginx config should do it:
```
# captchas
location ~ /captcha/.*\.jpg$ {
	access_log off;
	expires 0;
	root /path/to/jschan/static;
	try_files $uri =404;
}
```
The images are really small so it shouldn't make a huge difference in speed.

Also, I switched to gitgud https://gitgud.io/fatchan/jschan after [Githubs latest good idea](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) so post further updates there. 

Thanks!

**Comment by hawkoon** [comment]
I totally understand the move away from Github. I'm too lazy to create an account on GG though, I'll just lurk there for now. Hoping (You)s, custom board spoiler and Tor support will happen soon.

Anyway, I added your proposed solution to the nginx config and rebooted the server but no luck; 
the same problem with PM remains. The fact that every other browser does play nice with javascript disabled makes me think the problem simply _is_ with Pale Moon but they're too proud (or lazy) to admit it. Anyway, perhaps see you on the other side.
