### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by hackdefendr** [fatchan/jschan#164]
Hello...

First off, just awesome work with jschan so far. My friend and business partner are currently running it, despite your warnings, and are just fascinated. It has forced us to formally learn some new technologies and we have pretty much spent two weeks straight doing just that.

I personally am loving the pug template system. Jon, my biz partner, is diving into the database side. We have learned so much already, but are missing something.  Your vision. Do you have a more detailed roadmap for what's next with jschan. For example, will you be implementing a user management system?

Better yet, would you be open to jumping into a slack channel to chat? We'd love to pick your brain on when you think jschan will be production ready.

Here is our demo domain where we are running jschan: http://demo2.unfufadoo.net/index.html

We pronounce it...Unf Oofa Doo and it means nonsense from the old IRC days.

Take care.

**Comment by fatchan** [comment]
Hey, glad you're having fun with jschan.

Vision is a bit grand, but I did ask myself "how hard is it to make an imageboard software". Turns out not too hard. Ultimately I want an imageboard software that keeps the traditional look, adds some modern niceties, allows a lot of customisation and respects privacy/anonymity. 

Roadmap is: Fix breaking bugs > Add hidden service support -> Everything else. No trello or github projects at the moment. As for user management, right now it allows editing permission level or deleting accounts. I'm open to suggestion or PR for new features, it just depends what you have in mind.

I'm not open to joining a chat at this time. 

Cheers.

**Comment by hackdefendr** [comment]
Thanks for replying! Don't worry about the chat, I was just throwing that out there.

As for suggestions, implement a responsive theme that works on both desktop and mobile. That is what I am looking for most. User management is probably fine since keeping it anonymous is one of the goals. If I make any progress on my dev box I'll figure out how to make a PR from it.
