### ISSUE TITLE
Theme sets

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#41]
It might be a good idea to read through these iamgeboards and see what theme elements are required
- https://boards.systemspace.link
- https://www.lainchan.org
- https://arisuchan.jp
- https://dangeru.us
- https://wirechan.org
- http://spacechan.xyz
- https://mewch.net
- http://ronery.me
- https://loli.vodka
- https://www.meepmorp.net
- https://meguca.org
- http://bunkerchan.xyz
- http://endchan.org
- https://fapchan.org
- https://waifuist.pro
- https://einskanal.net
- https://bbw-chan.nl
- https://kek.fun
- https://indiachan.com

**Comment by DonaldTsang** [comment]
@fatchan best we can do is to breakdown all the included CSS and see what components are called, and from that create a universal CSS foramt set that allows `lynxchan => jschan` conversions.

**Comment by fatchan** [comment]
AAH my mistake. Im not sure it would be totally possible to convert themes. Not just because of naming, but because there are elements that exist or dont exist in lynxchan, jschan, vichan, etc that would be incompatible. That is why I suggested vars. Each theme has different colours, paddings, border radius that can be put into variables and used to transform default theme into another theme. There will be some work involved collecting colours, but I think it will be easier than trying to adapt CSS from different frontends to eachother.

Also, templates need to be improved first to output nicer, semantic HTML5.

**Comment by DonaldTsang** [comment]
@fatchan ease of hand conversion is key, not necessarily complete auto conversion, but we do need to do some work on understanding how lynxchan and vichan works before we design our own.

Perhaps we can start a "study" on how they work?

**Comment by fatchan** [comment]
Just putting these here since i forgot to add "references #xxx" in the commit message
Per-board theme option d8f98a67cb32f7a6f9451f16d4896eef3e0af234
More themes 1a44a71cef0977f2e36ca96d5cfeb4d50fd20f6f
Theme selection for js users b85afbb0db820c0854c023cda4ad287f1cb53624

**Comment by fatchan** [comment]
There are now many themes.
