### ISSUE TITLE
suggestion: dropping bcrypt

### ISSUE THREAD

**Issue by StephenLynx** [fatchan/jschan#8]
In my experience, bcrypt is one of the most troublesome dependencies to work with. From installation issues with lynxchan, bcrypt is easily the one that most people had issues with. Node ships with pbkdf2, which despite requiring a bit more of work to be used properly, won't give anyone headaches on installation. Sure there are pros and cons between the both as far as security goes, but pbkdf2 is good enough to be recommended by some authority that I can't remember now about it.

**Comment by fatchan** [comment]
Yes, I am aware of the security differences between bcrypt and pbkdf2. I'm not a crypto expert so its hard for me to decide which is more secure :thinking: 

As for installation difficulty, _personally_ i have had no problems getting it working on debian, ubuntu or arch. (i dont even remember having to do anything special at all... it just worked) Actually, there are pure javascript implementations on npmjs since im guessing the issue was some dependencies that people are missing? But I will keep this in mind. Closing for now.
