### ISSUE TITLE
database design issue

### ISSUE THREAD

**Issue by StephenLynx** [fatchan/jschan#9]
I noticed that you create separate collections for boards. That bad design. It will make harder to add boards and handle boards in general. Even a simple board listing will be much harder because you cant just do a find on a collection that holds all boards.

**Comment by fatchan** [comment]
yes I agree. its not worth splitting them into separate collections just for the sake of 1 less index. 

i needed to combine them into one anyway so that I can have something like
 captcha, tripcodes, boards, posts
as separate collections in a single database. right now i have them separate incase a board has the name "tripcodes" or "boards" which is a complete clusterfuck.

i dont think it will be a big deal to change. appreciate you popping by!

**Comment by StephenLynx** [comment]
About having board names that might conflict with something else, you could instead use routes to these functions to use a completely different format than boards. For example, if these features are inside .function/captcha, and you don't allow for dots on board URIs, then there's no way a board URI would cause an issue and you wouldn't need to make forbidden board URIs.

**Comment by fatchan** [comment]
yes, I use separate routes currently to make sure it wouldnt be a problem if i change to less collections. maybe i just explained it bad.

what i am saying is that _currently_, i am just doing something like `posts.collection(board).whatever(...)` since posts are 1 collection per board in a database. 

i will just make a single collection for posts and add a 'board' property to them i think. that makes it a million times easier and makes global post deletion for bans, etc more easy

**Comment by fatchan** [comment]
So i made some changes to consolidate the collections. Now i just need to figure out indexing to get minimum number of indexes but also support all the queries (probably more difficult now). 

On a side note, i feel like i need to slow down, do more brainstorming and figure out things 100% before i continue piling shit on thats half baked and will cause issues in future. Gonna work more on this next week when i have some time. until then im busy but will (inevitably) continue brainstorming :stuck_out_tongue: 

Cheers.

**Comment by StephenLynx** [comment]
Ah yeah, I thought I have gotten that wrong after I posted that. Also, yes, having separate collections for posts is awful to work with, because you need to do operations across boards very often. And about indexing, that can be figured out later when you implement features and know how exactly you will have to query your data.

I can also recommend using a documentation driven development. Where you first write down the relevant parts and only then you implement them. And since we're talking about databases, you will need a system where database changes are handled. For example, let's say you add a field on a collection that you have to use, there is no alternative, that data has to exist on those documents. But the old documents don't contain it, so you have to look for the documents that already exist and add that field, but only once. Basically, database versioning and updating.

**Comment by fatchan** [comment]
Yep. I probably wont make any database migration or update scripts until things are more set in stone (hopefully nobody uses this yet lmfao). But I have a good idea of how I will make one so it shouldn't be a problem.

Gonna close this for now as seems things are sorted.
